<?php

/*
 * This file is part of BedrockProtocol.
 * Copyright (C) 2014-2022 PocketMine Team <https://github.com/pmmp/BedrockProtocol>
 *
 * BedrockProtocol is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */

declare(strict_types=1);

namespace pocketmine\network\mcpe\protocol\types;

/**
 * @see MemoryCategoryCounter
 */
enum MemoryCategory : int{
	case UNKNOWN = 0;
	case INVALID_SIZE_UNKNOWN = 1;
	case ACTOR = 2;
	case ACTOR_ANIMATION = 3;
	case ACTOR_RENDERING = 4;
	case BLOCK_TICKING_QUEUES = 5;
	case BIOME_STORAGE = 6;
	case BLOBS = 7;
	case CEREAL = 8;
	case CIRCUIT_SYSTEM = 9;
	case CLIENT = 10;
	case COMMANDS = 11;
	case DB_STORAGE = 12;
	case DEBUG = 13;
	case DOCUMENTATION = 14;
	case ECS_SYSTEMS = 15;
	case FMOD = 16;
	case FONTS = 17;
	case IM_GUI = 18;
	case INPUT = 19;
	case JSON_UI = 20;
	case JSON_UI_CONTROL_FACTORY_JSON = 21;
	case JSON_UI_CONTROL_TREE = 22;
	case JSON_UI_CONTROL_TREE_CONTROL_ELEMENT = 23;
	case JSON_UI_CONTROL_TREE_POPULATE_DATA_BINDING = 24;
	case JSON_UI_CONTROL_TREE_POPULATE_FOCUS = 25;
	case JSON_UI_CONTROL_TREE_POPULATE_LAYOUT = 26;
	case JSON_UI_CONTROL_TREE_POPULATE_OTHER = 27;
	case JSON_UI_CONTROL_TREE_POPULATE_SPRITE = 28;
	case JSON_UI_CONTROL_TREE_POPULATE_TEXT = 29;
	case JSON_UI_CONTROL_TREE_POPULATE_TTS = 30;
	case JSON_UI_CONTROL_TREE_VISIBILITY = 31;
	case JSON_UI_CREATE_UI = 32;
	case JSON_UI_DEFS = 33;
	case JSON_UI_LAYOUT_MANAGER = 34;
	case JSON_UI_LAYOUT_MANAGER_REMOVE_DEPENDENCIES = 35;
	case JSON_UI_LAYOUT_MANAGER_INIT_VARIABLE = 36;
	case LANGUAGES = 37;
	case LEVEL = 38;
	case LEVEL_STRUCTURES = 39;
	case LEVEL_CHUNK = 40;
	case LEVEL_CHUNK_GEN = 41;
	case LEVEL_CHUNK_GEN_THREAD_LOCAL = 42;
	case LIGHT_VOLUME_MANAGER = 43;
	case NETWORK = 44;
	case MARKETPLACE = 45;
	case MATERIAL_DRAGON_COMPILED_DEFINITION = 46;
	case MATERIAL_DRAGON_MATERIAL = 47;
	case MATERIAL_DRAGON_RESOURCE = 48;
	case MATERIAL_DRAGON_UNIFORM_MAP = 49;
	case MATERIAL_RENDER_MATERIAL = 50;
	case MATERIAL_RENDER_MATERIAL_GROUP = 51;
	case MATERIAL_VARIATION_MANAGER = 52;
	case MOLANG = 53;
	case ORE_UI = 54;
	case ORE_UI_CLIENT = 55;
	case PERSONA_PIECES = 56;
	case PERSONA_ANIMATIONS = 57;
	case PERSONA_CHARACTERS = 58;
	case PERSONA_SKIN_PACKS = 59;
	case PERSONA_REPO = 60;
	case PLAYER = 61;
	case RENDER_CHUNK = 62;
	case RENDER_CHUNK_INDEX_BUFFER = 63;
	case RENDER_CHUNK_VERTEX_BUFFER = 64;
	case RENDERING = 65;
	case RENDERING_BGFX_INIT = 66;
	case RENDERING_BGFX_START_FRAME = 67;
	case RENDERING_BLOCK_TESSELLATOR = 68;
	case RENDERING_END_FRAME = 69;
	case RENDERING_GRAPHICS_TASKS_INIT = 70;
	case RENDERING_LIBRARY = 71;
	case RENDERING_POLYGON_OPERATOR_POOL = 72;
	case RENDERING_PBR_TEXTURE_DATA = 73;
	case RENDERING_RENDER_REGISTRY = 74;
	case RENDERING_SETUP = 75;
	case RENDERING_VERTICES = 76;
	case REQUEST_LOG = 77;
	case RESOURCE_PACKS = 78;
	case SOUND = 79;
	case SUB_CHUNK_BIOME_DATA = 80;
	case SUB_CHUNK_BLOCK_DATA = 81;
	case SUB_CHUNK_LIGHT_DATA = 82;
	case TEXTURES = 83;
	case WEATHER_RENDERER = 84;
	case WORLD_GENERATOR = 85;
	case TASKS = 86;
	case TEST = 87;
	case TEST_LOAD_TEST_TAGS = 88;
	case SCRIPTING = 89;
	case SCRIPTING_RUNTIME = 90;
	case SCRIPTING_CONTEXT = 91;
	case SCRIPTING_CONTEXT_BINDINGS_MC = 92;
	case SCRIPTING_CONTEXT_BINDINGS_GT = 93;
	case SCRIPTING_CONTEXT_RUN = 94;
	case DATA_DRIVEN_UI = 95;
	case DATA_DRIVEN_UI_DEFS = 96;
	case GAMEFACE = 97;
	case GAMEFACE_SYSTEM = 98;
	case GAMEFACE_DOM = 99;
	case GAMEFACE_CSS = 100;
	case GAMEFACE_DISPLAY = 101;
	case GAMEFACE_TEMP_ALLOCATOR = 102;
	case GAMEFACE_POOL_ALLOCATOR = 103;
	case GAMEFACE_DUMP = 104;
	case GAMEFACE_MEDIA = 105;
	case GAMEFACE_JSON = 106;
	case GAMEFACE_SCRIPT_ENGINE = 107;
	case GAMEFACE_SCRIPT = 108;
	case GAMEFACE_LAYOUT = 109;
}
